language: csharp
solution: ./src/Grapevine.sln
install:
  - nuget restore ./src/Grapevine.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./src/Grapevine.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/Grapevine.Test/bin/Release/Grapevine.Tests.dll